CREATE DATABASE SIAL_DB;
USE [SIAL_DB]; 				
SET LANGUAGE us_english;

--------CREANDO TABLAS---------

CREATE TABLE EQUIPO (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	MARCA VARCHAR(40) NOT NULL,
	NUMERO_SERIE VARCHAR(25) NOT NULL,
	CONTRATO_INICIO DATETIME,
	CONTRATO_FINAL DATETIME,
	DIRECCION VARCHAR(100) NOT NULL,
	VELOCIDAD FLOAT NOT NULL,
	VOLTAJE FLOAT NOT NULL,
	NIVELES INT NOT NULL
);

CREATE TABLE AUTOMOVIL (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	PLACA VARCHAR(9) NOT NULL,
	MODELO VARCHAR(25) NOT NULL,
	COMBUSTUBLE VARCHAR(12) NOT NULL,
	ANIO INT NOT NULL,
	MARCA VARCHAR (15) NOT NULL
);

CREATE TABLE MANTENIMIENTO (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	FECHA_MANTENIMIENTO DATETIME NOT NULL,
	NUMERO_SERIE VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(200),
	TECNICO VARCHAR(50),
	ESTADO VARCHAR (10) NOT NULL,
	ID_EQUIPO INT NULL,
	ID_AUTOMOVIL INT NULL
);

CREATE TABLE REPARACION (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	FECHA_REPARACION DATETIME NOT NULL,
	NUMERO_SERIE VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(200),
	TECNICO VARCHAR(50),
	ESTADO VARCHAR (10) NOT NULL,
	ID_EQUIPO INT NULL,
	ID_AUTOMOVIL INT NULL
);

CREATE TABLE REPARACIONxREPUESTO (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	ID_REPARACION INT NOT NULL,
	ID_REPUESTO INT NOT NULL
);

CREATE TABLE REPUESTO (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	MODELO VARCHAR(25) NOT NULL,
	NUMERO_SERIE VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(200),
	FABRICANTE VARCHAR(25),
	CANTIDAD INT NOT NULL,
	PRECIO FLOAT,
	TIEMPO_SUMINISTRO TIME
);

--------CREANDO FKs/PKs---------
ALTER TABLE REPARACION ADD FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID)
ALTER TABLE MANTENIMIENTO ADD FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID)
ALTER TABLE REPARACIONxREPUESTO ADD FOREIGN KEY (ID_REPARACION) REFERENCES REPARACION(ID)
ALTER TABLE REPARACIONxREPUESTO ADD FOREIGN KEY (ID_REPUESTO) REFERENCES REPUESTO(ID)
ALTER TABLE REPARACION ADD FOREIGN KEY (ID_AUTOMOVIL) REFERENCES AUTOMOVIL(ID)
ALTER TABLE MANTENIMIENTO ADD FOREIGN KEY (ID_AUTOMOVIL) REFERENCES AUTOMOVIL(ID)
